#TARGET: Prerequisites
#	commands

#The commands are a series of steps typically to make the target,
# need to start with a tab characterm, not space.

#The Prerequisites are file names, separated by sapces.
# these file need to exist before the commands for the target are run.

build: 
	g++ main.cc -o main

execute: 
	./main

clean: 
	rm -r main
